package org.anonymous.wallets.fullnode;
/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.anonymous.wallets.fullnode.daemon.ANONClientCaller;
import org.anonymous.wallets.fullnode.ui.ANONWalletUI;
import org.junit.Test;

import java.io.IOException;

import static org.junit.Assert.assertNotNull;

public class ANONWalletUITest {
    @Test
    public void testAppHasAGreeting() throws InterruptedException, ANONClientCaller.WalletCallException, IOException {
        ANONWalletUI classUnderTest = null;
        classUnderTest = new ANONWalletUI(null,"ANON Wallet TEST");
        assertNotNull("app should have a greeting", classUnderTest);
    }
}
